### PR TITLE
Skip running ifupdown in docker guests (and some simplifications on conditions)

### PR DESCRIPTION
**Pull request by htgoebel**
I had to simplify the conditions to understand them :-)

### CODE REVIEW

**Comment by drybjed** [comment]
Better way would be to check if we have capability to manage network interfaces at all (`cap_net_admin`) and act accordingly. I'm looking into a way to add that globally for all roles.

**Comment by htgoebel** [comment]
@drybjed I'll update for using the caps like in ferm.

**Comment by drybjed** [comment]
@htgoebel OK. I tried it in an LXC container with disabled `cap_net_admin` and Ansible didn't complain, but maybe it doesn't work after all. Do you get any error messages or is `ifupdown` silently ignoring the configuration in a Docker container?

**Comment by htgoebel** [comment]
@drybjed I got an error message, so 31e5ab6 currently checks for docker.
ATM I'm changing this to checking the caps. mompl.

**Comment by htgoebel** [comment]
Works as expected in my docker container.

**Pull request merged**
